---
output: pdf_document
fontsize: 12pt
header-includes:
  - \usepackage{leading}
  - \leading{18pt}
---

<!-- <style type="text/css"> -->

<!-- body{ /* Normal  */ -->
<!--       font-size: 14px; -->
<!--       line-height: 5; -->
<!--   } -->
<!-- </style> -->

\thispagestyle{empty}
&nbsp;
&nbsp;
\begin{large}
\noindent Research Master's programme 
Methodology and Statistics for the Behavioural, Biomedical and Social Sciences \newline
Utrecht University, the Netherlands \newline
\newline
\newline
\newline
\newline
MSc Thesis Hanne Ida Oberman (4216318) \newline
TITLE: ``Missing the Point: Non-Convergence in Iterative Imputation Algorithms'' \newline
May 2020 \newline
\newline
\newline
\newline
\newline
Supervisors:\newline
Prof. Dr. Stef van Buuren \newline
Dr. Gerko Vink \newline
\newline
\newline
Second grader(s): \newline
Prof. Dr. Jean-Paul Fox \newline
(Dr. Peter Lugtig) \newline
\newline
\newline
\newline
\newline
Preferred journal of publication: Sociological Methods \& Research \newline
Word count: ... \newline
\end{large}
\pagebreak

